name: Generic issue
description: For issues that do not fit any of the other categories.
title: _Replace With a Descriptive Title_
labels: wontfix
assignees: []
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: "Please provide a clear and concise description of what the question is."
      placeholder:
      value:
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: unimol_tools Version
      description: "The version of unimol_tools you are using."
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Details
      description: "Please explain the issue in detail here."
      placeholder:
      value:
    validations:
      required: true
  - type: markdown
    attributes:
      value: >
        Thanks for contributing 🎉!
